### ISSUE TITLE
protoDUNE-SP noise spectra file

### ISSUE THREAD

**Issue by brettviren** [WireCell/wire-cell-data#1]
A file of suitable noise spectra is required for protoDUNE-SP simulation.

The one for MB is https://github.com/WireCell/wire-cell-data/blob/master/microboone-noise-spectra-v2.json.bz2

If the data is provided in the so called "microboonev1" format there is an existing converter: `wirecell-sigproc convert-noise-spectra`.   That format is documented in the comments here:

https://github.com/WireCell/wire-cell-python/blob/master/wirecell/sigproc/noise/microboone.py#L16

Or, new formats can be added to that command starting at:

https://github.com/WireCell/wire-cell-python/blob/master/wirecell/sigproc/main.py#L232

**Comment by goowenq** [comment]
done.
