### ISSUE TITLE
VD-coldbox wires file 

### ISSUE THREAD

**Issue by brettviren** [WireCell/wire-cell-data#3]
We need a "wires file" for the VD coldbox being tested at CERN.

A diagram for what LArSoft supplies is here:

 https://cdcvs.fnal.gov/redmine/attachments/65632/chanmap_offline_numbers_detector_strips.pdf

The wires file should **exclude** any of the "ghost" channels given in red in the diagram.  Instead, these strips should be given as having segment number "1" (counting from 0) and be given the offline channel ID of the "real" channel to which it contributes via its jumpered segment=0 neighbor.

**Comment by nitish-nayak** [comment]
Hi @brettviren Do I have write access to this repo? I have the wires file but pushing it gives me 
```
ERROR: Permission to WireCell/wire-cell-data.git denied to nitish-nayak.
```

Maybe I'm doing something stupid. My remote-url is 
```   
origin  git@github.com:WireCell/wire-cell-data.git 
````

**Comment by brettviren** [comment]
Hi @nitish-nayak You should have write access now.  Your remote-url looks good.

**Comment by nitish-nayak** [comment]
Okay, I committed the wires file. There's somethings that I wanted to clarify but. So the Wires objects in the schema come with Tom's offline channel numbers + segment numbers for the jumpered wires like we discussed, and this is reflected in the file. But for the Planes objects in this, I see : 
```
"planes": [                                          
      {                                                                     
        "Plane": {                                                  
          "ident": 0,                                                      
          "wires": [                                 
            0,                                                               
            1,                                                             
            2,                                                                 
            3,                                                        
            4,                                                           
            5,                                                               
            6,                                                               
            7,                                           
            8,       
            9,                                     
            10,                                                    
            11,                                          
            12,                                                             
            13,                                             
``` 
and these wire numbers aren't channel numbers but seem like an internal wct index corresponding to the lines read from a wire dump file, for eg here : https://github.com/WireCell/wire-cell-python/blob/master/wirecell/util/wires/dunevd.py#L55

In particular, the wire number here corresponding to say, offline channel 255 that is jumpered using two segments are 255 and 1855. 

Am I interpreting this correctly? If so, is this an issue? Does the sigproc stage assume the wire numbers here inside "Planes" correspond exactly to channel numbers?

**Comment by brettviren** [comment]
Right, these are indices in to the array found in the `Store.wires` array.  One element there is like:

```
bzcat dunevdcb1-3view-wires-v1.json.bz2 |jq '.Store.wires[0]'
```

```json
{
  "Wire": {
    "ident": 0,
    "channel": 0,
    "segment": 0,
    "tail": 0,
    "head": 1
  }
}
```
This JSON file is like a little database so has a few indirections that are not very human-friendly.

For something slightly more human friendly, you can run:

```
wirecell-util plot-wires  dunevdcb1-3view-wires-v1.json.bz2 wires.pdf
```

To generate many pages of diagnostic plots. These plots may not make immediate sense but they display many of the salient features.  Feel free to add yet more plots to that command if you feel like it. (just do so in a way that is general to all detectors).  Or, if you come up with your own plots, even if they are detector specific, feel free to add them to a `wire-cell-python` command.

**Comment by nitish-nayak** [comment]
thank you! yeah, it makes sense now. So I think everything seems as expected then.
